# Generated by Django 4.2.15 on 2024-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_date", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="insurancepolicy", name="policy_number",),
        migrations.AddField(
            model_name="insurancepolicy",
            name="policy_name",
            field=models.TextField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="policy_nunber",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
