# Generated by Django 4.2.15 on 2024-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_date", "0002_remove_insurancepolicy_policy_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancepolicy",
            name="policy_message",
            field=models.TextField(default=20, max_length=100),
            preserve_default=False,
        ),
    ]
