# Generated by Django 4.2.15 on 2024-08-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_date", "0003_insurancepolicy_policy_message"),
    ]

    operations = [
        migrations.RemoveField(model_name="stockholding", name="user",),
        migrations.RemoveField(model_name="transaction", name="holding",),
        migrations.DeleteModel(name="InsurancePolicy",),
        migrations.DeleteModel(name="StockHolding",),
        migrations.DeleteModel(name="Transaction",),
        migrations.DeleteModel(name="User",),
    ]
