# Generated by Django 4.2.15 on 2024-09-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_date", "0006_rename_user_enduser"),
    ]

    operations = [
        migrations.RemoveField(model_name="insurancepolicy", name="user",),
        migrations.RemoveField(model_name="stockholding", name="user",),
        migrations.DeleteModel(name="EndUser",),
    ]
