# Generated by Django 4.2.15 on 2024-09-03 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "insurance_date",
            "0007_remove_insurancepolicy_user_remove_stockholding_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance_date.enduser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockholding",
            name="user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance_date.enduser",
            ),
            preserve_default=False,
        ),
    ]
