# Generated by Django 4.2.15 on 2024-09-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_date", "0008_enduser_insurancepolicy_user_stockholding_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="insurancepolicy", name="policy_nunber",),
    ]
